#include "CrazyCubeImproved.h"

CrazyCubeImproved:: CrazyCubeImproved()
{
    // Set cube as solved
    outerEdges = 0;
    outerCorners = 0;
    innerEdges = 0xF; // accordingly: 0 0 0 0 in top layer, 1 1 1 1 in bottom layer
    innerCorners = 0x7; // the same: 0 0 0 0, 1 1 1
    centre = 1;

    // Initialise moves array 
    for (int i = 0; i < NUM_OF_MOVES; ++i)
    {
        movesInversions[i] = i;
    }

    this->cache = new CrazyCubeCache;
    this->mapper = new CrazyCubeMapper;

    // Pass move maps - generated by mapper, passed to cube by cache
    cache->setOuterCornersMap(mapper->generateOuterCornersMap());
    cache->setInnerCornersMap(mapper->generateInnerCornersMap());
    cache->setOuterEdgesMap(mapper->generateOuterEdgesMap());
    cache->setInnerEdgesMap(mapper->generateInnerEdgesMap());
    cache->setCentreMap(mapper->generateCentreMap());

    // Set the maps
    // this->setCrazyCubeCache(cache);
}


CrazyCubeImproved:: ~CrazyCubeImproved()
{
    delete cache;
    delete mapper;
}

void CrazyCubeImproved:: resetCube()
{
    outerEdges = 0;
    outerCorners = 0;
    innerEdges = 0xF;
    innerCorners = 0x7;
    centre = 1;
}

void CrazyCubeImproved:: setOuterCorners(int outerCorners)
{
	this->outerCorners = outerCorners;
}

void CrazyCubeImproved:: setInnerCorners(int innerCorners)
{
	this->innerCorners = innerCorners;
}

void CrazyCubeImproved:: setOuterEdges(int outerEdges)
{
	this->outerEdges = outerEdges;
}

void CrazyCubeImproved:: setInnerEdges(int innerEdges)
{
	this->innerEdges = innerEdges;
}

void CrazyCubeImproved:: setCentre(int centre)
{
	this->centre = centre;
}

void CrazyCubeImproved:: setCube(int outerCorners, int innerCorners, int outerEdges, int innerEdges, int centre)
{
	setOuterCorners(outerCorners);
	setInnerCorners(innerCorners);
	setOuterEdges(outerEdges);
	setInnerEdges(innerEdges);
	setCentre(centre);
}

int CrazyCubeImproved:: getOuterCorners()
{
	return outerCorners;
}

int CrazyCubeImproved:: getInnerCorners()
{
	return innerCorners;
}

int CrazyCubeImproved:: getOuterEdges()
{
	return outerEdges;
}

int CrazyCubeImproved:: getInnerEdges()
{
	return innerEdges;
}

int CrazyCubeImproved:: getCentre()
{
	return centre;
}


void CrazyCubeImproved:: move(unsigned short int m)
{
	outerCorners = cache->getOuterCornersMap()[outerCorners][m];
	innerCorners = cache->getInnerCornersMap()[innerCorners][m];
	outerEdges = cache->getOuterEdgesMap()[outerEdges][m];
	innerEdges = cache->getInnerEdgesMap()[innerEdges][m];
	centre = cache->getCentreMap()[centre][m];
}


void CrazyCubeImproved:: undoMove(unsigned short int m)
{
	outerCorners = cache->getOuterCornersMap()[outerCorners][movesInversions[m]];
	innerCorners = cache->getInnerCornersMap()[innerCorners][movesInversions[m]];
	outerEdges = cache->getOuterEdgesMap()[outerEdges][movesInversions[m]];
	innerEdges = cache->getInnerEdgesMap()[innerEdges][movesInversions[m]];
	centre = cache->getCentreMap()[centre][movesInversions[m]];
}


void CrazyCubeImproved:: printCubeState()
{
	cout << "outerCorners: " << outerCorners << endl;
	cout << "innerCorners: " << innerCorners << endl;
	cout << "outerEdges: " << outerEdges << endl;
	cout << "innerEdges: " << innerEdges << endl;
	cout << "centre: " << centre << endl;
}

bool CrazyCubeImproved:: isSolved()
{
    return (outerEdges == 0)    && 
           (outerCorners == 0)  &&
           (innerEdges == 0xF)  &&
           (innerCorners == 0x7)&&
           (centre == 1);

}

